development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: blog_development
  host: 127.0.0.1
  pool: 5
  username: root
  password: mysql
  socket: /opt/local/var/run/mysql5/mysqld.sock
test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: blog_test
  host: 127.0.0.1
  pool: 5
  username: root
  password: mysql
  socket: /opt/local/var/run/mysql5/mysqld.sock
production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: blog_production
  host: 127.0.0.1
  pool: 5
  username: root
  password: mysql
  socket: /opt/local/var/run/mysql5/mysqld.sock